#!/bin/bash
set -e

# ============================================================================
# Cardano mainnet db-sync — full setup script
#
# Installs cardano-node + cardano-db-sync + PostgreSQL via Docker Compose
# into /Users/nhenin/dev/local-infra/cardano-dbsync
#
# Prerequisites: Docker Desktop for Mac (with enough disk — need ~300 GB)
#
# Usage:
#   bash spo-incentives/mainnet-indexer/setup.sh
#
# After setup, connect to PostgreSQL:
#   psql -h localhost -p 5433 -U postgres -d cexplorer
# ============================================================================

INFRA_DIR="/Users/nhenin/dev/local-infra/cardano-dbsync"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "============================================"
echo "  Cardano db-sync — mainnet setup"
echo "  Target: $INFRA_DIR"
echo "============================================"
echo ""

# --- 1. Check Docker ---
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is not installed."
    echo "  Install Docker Desktop for Mac: https://www.docker.com/products/docker-desktop/"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo "ERROR: Docker daemon is not running. Start Docker Desktop first."
    exit 1
fi

echo "[OK] Docker is available"

# --- 2. Check disk space ---
AVAILABLE_GB=$(df -g /Users/nhenin | tail -1 | awk '{print $4}')
echo "Available disk space: ${AVAILABLE_GB} GB"
if [ "$AVAILABLE_GB" -lt 200 ]; then
    echo "WARNING: Less than 200 GB free. db-sync needs ~250-300 GB total."
    echo "  node data: ~100 GB"
    echo "  PostgreSQL: ~150 GB"
    echo ""
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# --- 3. Create directory structure ---
echo ""
echo "Creating directory structure..."
mkdir -p "$INFRA_DIR/secrets"
mkdir -p "$INFRA_DIR/snapshots"

# --- 4. Create secrets ---
echo "postgres" > "$INFRA_DIR/secrets/postgres_user"
echo "cexplorer" > "$INFRA_DIR/secrets/postgres_db"

# Generate or reuse password
if [ ! -f "$INFRA_DIR/secrets/postgres_password" ]; then
    openssl rand -hex 16 > "$INFRA_DIR/secrets/postgres_password"
    echo "  Generated new PostgreSQL password"
else
    echo "  Reusing existing PostgreSQL password"
fi

chmod 600 "$INFRA_DIR/secrets/"*

# --- 5. Copy docker-compose.yml ---
cp "$SCRIPT_DIR/docker-compose.yml" "$INFRA_DIR/docker-compose.yml"
echo "  Copied docker-compose.yml"

# --- 6. Create .env for convenience ---
PG_PASS=$(cat "$INFRA_DIR/secrets/postgres_password")
cat > "$INFRA_DIR/.env" << EOF
# Cardano db-sync configuration
# Generated by setup.sh

# Set RESTORE_SNAPSHOT to a snapshot file path to speed up initial sync.
# Download from: https://github.com/IntersectMBO/cardano-db-sync/releases
# Example:
#   RESTORE_SNAPSHOT=/snapshots/db-sync-snapshot-schema-13.7-block-XXXXX-x86_64.tgz
RESTORE_SNAPSHOT=

# Extra db-sync args (optional)
EXTRA_DB_SYNC_ARGS=
EOF

# --- 7. Create connection helper ---
cat > "$INFRA_DIR/connect.sh" << EOF
#!/bin/bash
# Connect to the db-sync PostgreSQL instance
psql "postgresql://postgres:${PG_PASS}@localhost:5433/cexplorer"
EOF
chmod +x "$INFRA_DIR/connect.sh"

# --- 8. Create convenience scripts ---
cat > "$INFRA_DIR/start.sh" << 'EOF'
#!/bin/bash
cd "$(dirname "$0")"
docker compose up -d
echo ""
echo "Services starting. Monitor with:"
echo "  docker compose logs -f"
echo "  docker compose logs -f cardano-db-sync"
echo ""
echo "Check sync progress:"
echo "  docker compose exec postgres psql -U postgres -d cexplorer -c \"SELECT MAX(epoch_no) FROM epoch_stake;\""
EOF
chmod +x "$INFRA_DIR/start.sh"

cat > "$INFRA_DIR/stop.sh" << 'EOF'
#!/bin/bash
cd "$(dirname "$0")"
docker compose down
EOF
chmod +x "$INFRA_DIR/stop.sh"

cat > "$INFRA_DIR/status.sh" << 'EOF'
#!/bin/bash
cd "$(dirname "$0")"
echo "=== Container status ==="
docker compose ps
echo ""
echo "=== Node sync progress ==="
docker compose exec cardano-node cardano-cli query tip --mainnet 2>/dev/null || echo "(node not ready yet)"
echo ""
echo "=== DB-sync progress ==="
docker compose exec postgres psql -U postgres -d cexplorer -t -c \
    "SELECT 'Latest block: ' || COALESCE(MAX(block_no)::text, 'n/a') FROM block;" 2>/dev/null || echo "(db not ready yet)"
docker compose exec postgres psql -U postgres -d cexplorer -t -c \
    "SELECT 'Latest epoch_stake: ' || COALESCE(MAX(epoch_no)::text, 'n/a') FROM epoch_stake;" 2>/dev/null || echo ""
EOF
chmod +x "$INFRA_DIR/status.sh"

# --- 9. Store connection string for our pipeline ---
CONN_STR="postgresql://postgres:${PG_PASS}@localhost:5433/cexplorer"
echo "$CONN_STR" > "$INFRA_DIR/connection_string.txt"
chmod 600 "$INFRA_DIR/connection_string.txt"

# --- 10. Print summary ---
echo ""
echo "============================================"
echo "  Setup complete!"
echo "============================================"
echo ""
echo "Directory:  $INFRA_DIR"
echo ""
echo "Files created:"
echo "  docker-compose.yml     Docker Compose stack"
echo "  secrets/               PostgreSQL credentials"
echo "  .env                   Environment config"
echo "  start.sh               Start all services"
echo "  stop.sh                Stop all services"
echo "  status.sh              Check sync progress"
echo "  connect.sh             Open psql shell"
echo "  connection_string.txt  For our ingest_dbsync.py"
echo ""
echo "NEXT STEPS:"
echo ""
echo "  1. (Optional but recommended) Download a db-sync snapshot"
echo "     to skip days of initial sync:"
echo ""
echo "     Check latest snapshot at:"
echo "       https://github.com/IntersectMBO/cardano-db-sync/releases"
echo ""
echo "     Download it to $INFRA_DIR/snapshots/"
echo "     Then edit $INFRA_DIR/.env and set:"
echo "       RESTORE_SNAPSHOT=/snapshots/<filename>.tgz"
echo ""
echo "  2. Start the stack:"
echo ""
echo "     cd $INFRA_DIR"
echo "     bash start.sh"
echo ""
echo "  3. Monitor sync progress:"
echo ""
echo "     bash status.sh"
echo "     docker compose logs -f cardano-db-sync"
echo ""
echo "  4. Once synced, export the connection string for downstream pipelines:"
echo ""
echo "     export DBSYNC_CONN_STR=\"\$(cat $INFRA_DIR/connection_string.txt)\""
echo ""
echo "  Sync time estimate:"
echo "    - With snapshot: ~12-24 hours"
echo "    - Without snapshot: ~3-5 days"
echo ""
