#!/usr/bin/env python3
"""Regenerate the static website from Markdown sources.

Usage:
    python3 build_site.py [page_slug ...]

Without arguments, regenerates all pages. With slugs, only the named pages
are regenerated.

Per-page contract:
- MD source → HTML output in generated-website/
- Relative image paths in the MD are rewritten to the mirrored location
  inside generated-website/ (the "diagnostic/" prefix is stripped because
  the mirroring convention collapses that level).
- Cross-page links (*.md with or without #anchor) are rewritten to the
  corresponding .html file using MD_TO_HTML_MAP.
- Anchors are generated by python-markdown's TOC slugifier, which matches
  the convention used by the previous HTML (kebab-case, numbers collapsed).
- Math (``$...$`` inline, ``$$...$$`` display) is protected during MD parsing
  so underscores inside math do not trigger italic rendering, then restored
  verbatim for MathJax to render client-side.
"""

from __future__ import annotations

import hashlib
import html as _html
import re
import shutil
import sys
import time
from pathlib import Path

import markdown

# --- Paths ----------------------------------------------------------------

SITE_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SITE_DIR.parent.resolve()  # reward-system-spec/

# --- Page configuration ---------------------------------------------------

# Each page: slug, source MD (relative to REPO_ROOT), output HTML name,
# hero label/h1/sub, active nav tab (None for home).
PAGES = [
    {
        "slug": "index",
        "md": "README.md",
        "html": "index.html",
        "title": "The Cardano Reward System V2 — Specification for a Sustainable Successor",
        "hero_h1": "The Cardano Reward System V2",
        "hero_sub": "Specification for a Sustainable Successor",
        "active_nav": "spec",
    },
    {
        "slug": "intended-game",
        "md": "the-intended-game/README.md",
        "html": "intended-game.html",
        "title": "The Intended Game — SPO Incentives",
        "hero_h1": "The Intended Game",
        "hero_sub": "A Narrative Description of the Consensus Incentive Mechanism",
        "active_nav": "intended-game",
    },
    {
        "slug": "observatory",
        "md": "diagnostic/README.md",
        "html": "observatory.html",
        "title": "The Diagnostic — Mainnet Observatory",
        "hero_h1": "The Diagnostic — Mainnet Observatory",
        "hero_sub": "Synthesis of Observations Across the Reward Pipeline",
        "active_nav": "observatory",
    },
    {
        "slug": "census",
        "md": "diagnostic/sub-flows/census/mainnet-analysis/README.md",
        "html": "census.html",
        "title": "The Staking Census — SPO Incentives",
        "hero_h1": "The Staking Census",
        "hero_sub": "Populations, Capital, and Participation",
        "active_nav": "census",
    },
    {
        "slug": "treasury",
        "md": "diagnostic/sub-flows/treasury-and-pool-pots-distribution/mainnet-analysis/README.md",
        "html": "treasury.html",
        "title": "Treasury & Pool Pots Distribution — SPO Incentives",
        "hero_h1": "Treasury & Pool Pots Distribution",
        "hero_sub": "Mainnet Analysis — Stage 1",
        "active_nav": "treasury",
    },
    {
        "slug": "pools",
        "md": "diagnostic/sub-flows/pools-distribution/mainnet-analysis/README.md",
        "html": "pools.html",
        "title": "The Pools Pot Distribution Gaps — SPO Incentives",
        "hero_h1": "The Pools Pot Distribution Gaps",
        "hero_sub": "Mainnet Analysis — Stage 2",
        "active_nav": "pools",
    },
    {
        "slug": "operator",
        "md": "diagnostic/sub-flows/operator-delegator-distribution/mainnet-analysis/README.md",
        "html": "operator.html",
        "title": "The Operator's Cut — SPO Incentives",
        "hero_h1": "The Operator's Cut",
        "hero_sub": "Mainnet Analysis — Stage 3",
        "active_nav": "operator",
    },
]

# MD path (relative to REPO_ROOT) → output HTML filename
MD_TO_HTML_MAP = {p["md"]: p["html"] for p in PAGES}


# --- Math protection ------------------------------------------------------

_MATH_PLACEHOLDER = "@@MATH{idx}@@"


def protect_math(text: str) -> tuple[str, list[str]]:
    """Replace $...$ and $$...$$ spans with placeholders to keep markdown
    from interpreting underscores, asterisks, etc. inside them.

    Returns (text_with_placeholders, list_of_original_spans).
    """
    spans: list[str] = []

    # Display math ($$...$$) first (so it's not captured by inline).
    def _store(match: re.Match) -> str:
        idx = len(spans)
        spans.append(match.group(0))
        return _MATH_PLACEHOLDER.format(idx=idx)

    text = re.sub(r"\$\$(.+?)\$\$", _store, text, flags=re.DOTALL)
    # Inline math — exclude cases where $ is preceded/followed by digit/letter
    # without space (currency-style). Keep it permissive: any paired $...$ on
    # a single line, with no $ inside.
    text = re.sub(r"(?<!\\)\$([^\$\n]+?)\$", _store, text)
    return text, spans


def restore_math(html: str, spans: list[str]) -> str:
    for idx, span in enumerate(spans):
        html = html.replace(_MATH_PLACEHOLDER.format(idx=idx), span)
    return html


# --- Link & image rewriting -----------------------------------------------


def _resolve_rel(src_md: Path, target: str) -> Path:
    return (src_md.parent / target).resolve()


def _rel_to_site(src_md: Path, target: str) -> str:
    """Compute a path suitable for the HTML output (relative to SITE_DIR),
    given a relative path written in the MD.

    Convention: if the resolved path lies under diagnostic/, the leading
    "diagnostic/" is stripped, because figures are mirrored into
    generated-website/ without that prefix.
    """
    target_abs = _resolve_rel(src_md, target)
    try:
        rel = target_abs.relative_to(REPO_ROOT)
    except ValueError:
        # Outside repo root — return as-is
        return target
    rel_str = rel.as_posix()
    if rel_str.startswith("diagnostic/"):
        rel_str = rel_str[len("diagnostic/"):]
    return rel_str


def rewrite_md_link(link: str, src_md: Path) -> str:
    """Rewrite a MD-source link for the HTML output."""
    if not link or link.startswith(("#", "http://", "https://", "mailto:", "tel:", "ftp://")):
        return link
    # Split out anchor
    anchor = ""
    if "#" in link:
        link, anchor = link.split("#", 1)
        anchor = "#" + anchor
    # .md links → map to .html
    if link.endswith(".md"):
        target_abs = _resolve_rel(src_md, link)
        try:
            rel = target_abs.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            return link + anchor
        if rel in MD_TO_HTML_MAP:
            return MD_TO_HTML_MAP[rel] + anchor
        # Unknown MD: keep but warn
        print(f"  warn: unmapped MD link → {rel}", file=sys.stderr)
        return link + anchor
    # Other relative paths (figures, directories): rewrite to site-relative
    return _rel_to_site(src_md, link) + anchor


_TOC_BLOCK_RE = re.compile(
    r"(^#{1,2}\s+Table of Contents\s*\n)([\s\S]*?)(?=^#{1,6}\s|^---\s*$|\Z)",
    re.MULTILINE,
)


_LIST_ITEM_RE = re.compile(r"^(\d+\.|[-*+])\s")


def _normalize_toc_indent(block: str) -> str:
    """Re-indent a TOC block so each nesting level is exactly 4 spaces.

    The source MDs use ad-hoc indentation: 3 spaces for the first sub-level,
    5–6 spaces for the second, 7–9 for the third, etc. python-markdown's
    ``sane_lists`` requires strict 4-space indentation per level, otherwise
    nested lines are folded into the parent item as text.

    This walks the block line-by-line, tracks observed indents on a stack,
    and emits ``level * 4`` spaces in front of each list-item line.
    """
    lines = block.splitlines(keepends=True)
    indents: list[int] = []  # ascending stack of indent widths observed
    out: list[str] = []
    for line in lines:
        stripped = line.lstrip(" ")
        if not stripped.strip():
            out.append(line)
            continue
        if not _LIST_ITEM_RE.match(stripped):
            # Not a list marker — keep original indent
            out.append(line)
            continue
        indent = len(line) - len(stripped)
        # Pop deeper levels that no longer apply
        while indents and indent < indents[-1]:
            indents.pop()
        if not indents or indent > indents[-1]:
            indents.append(indent)
        level = len(indents) - 1
        out.append(" " * (level * 4) + stripped)
    return "".join(out)


def normalize_toc_indentation(md_text: str) -> str:
    """Find the Table of Contents block and normalize its indentation."""
    def _sub(m: re.Match) -> str:
        return m.group(1) + _normalize_toc_indent(m.group(2))

    return _TOC_BLOCK_RE.sub(_sub, md_text, count=1)


def preprocess_md(md_text: str, src_md: Path) -> str:
    """Rewrite MD links/images before feeding to the markdown parser.

    Using the MD source representation keeps python-markdown's TOC slugifier
    working the same way as the rest of the page (we don't need to touch the
    rendered HTML for anchors). We only rewrite the path part of ``[..](..)``
    and ``![..](..)`` constructs.
    """
    md_text = normalize_toc_indentation(md_text)
    # Images: ![alt](path)  — the path may include a title "title"
    img_re = re.compile(r"(!\[[^\]]*\]\()([^)\s]+)(\s+\"[^\"]*\")?(\))")

    def _img_sub(m: re.Match) -> str:
        prefix, path, title, suffix = m.group(1), m.group(2), m.group(3) or "", m.group(4)
        # External or anchor-only: keep
        if path.startswith(("http://", "https://", "data:", "/", "#")):
            return m.group(0)
        new_path = _rel_to_site(src_md, path)
        return f"{prefix}{new_path}{title}{suffix}"

    md_text = img_re.sub(_img_sub, md_text)

    # Links: [text](path)  — but not images (which are ![...])
    link_re = re.compile(r"(?<!\!)(\[(?:[^\[\]]|\[[^\]]*\])*\]\()([^)\s]+)(\s+\"[^\"]*\")?(\))")

    def _link_sub(m: re.Match) -> str:
        prefix, path, title, suffix = m.group(1), m.group(2), m.group(3) or "", m.group(4)
        new_path = rewrite_md_link(path, src_md)
        return f"{prefix}{new_path}{title}{suffix}"

    md_text = link_re.sub(_link_sub, md_text)
    return md_text


# --- Markdown → HTML ------------------------------------------------------


def md_to_html(md_text: str) -> str:
    """Convert Markdown to HTML with our extension set.

    Math is protected around the conversion so $...$ contents pass through
    verbatim for MathJax.
    """
    md_text, math_spans = protect_math(md_text)

    md = markdown.Markdown(
        extensions=[
            "tables",
            "fenced_code",
            "attr_list",
            "sane_lists",
            "footnotes",
            "md_in_html",
            "toc",
        ],
        extension_configs={
            "toc": {"permalink": False, "anchorlink": False},
        },
        output_format="html5",
    )
    html_out = md.convert(md_text)
    html_out = restore_math(html_out, math_spans)
    html_out = _mermaidize(html_out)
    return html_out


# --- Mermaid: promote fenced ``` mermaid ``` to <div class="mermaid"> -----

_MERMAID_RE = re.compile(
    r'<pre><code class="(?:language-)?mermaid">([\s\S]*?)</code></pre>',
    re.IGNORECASE,
)


def _mermaidize(html_out: str) -> str:
    """Replace Mermaid code fences with divs so the client-side mermaid.js
    library can render them as SVG. The code content is HTML-unescaped so the
    original Mermaid source (including ``<b>`` and ``<br/>`` in node labels)
    is handed to the renderer verbatim.
    """
    def _sub(m: "re.Match[str]") -> str:
        return f'<div class="mermaid">{_html.unescape(m.group(1))}</div>'
    return _MERMAID_RE.sub(_sub, html_out)


# --- TOC wrapping (promote manual TOC to <nav class="toc-nav">) -----------


_TOC_HEADING_RE = re.compile(
    r'<h[12][^>]*id="table-of-contents"[^>]*>Table of Contents</h[12]>',
    re.IGNORECASE,
)
_LIST_OPEN_RE = re.compile(r"<(?:ul|ol)\b[^>]*>", re.IGNORECASE)
_LIST_TAG_RE = re.compile(r"<(/?)(ul|ol)\b[^>]*>", re.IGNORECASE)


def _find_matching_list_end(html: str, start: int) -> int:
    """Starting at index ``start`` (pointing at ``<ul`` or ``<ol``), return the
    index just past the matching closing list tag, using depth counting so
    nested lists don't close the outer too early.

    Tracks both ``<ul>`` and ``<ol>`` together; returns -1 if no matching close.
    """
    depth = 0
    pos = start
    while pos < len(html):
        m = _LIST_TAG_RE.search(html, pos)
        if not m:
            return -1
        if m.group(1) == "":  # opening
            depth += 1
        else:  # closing
            depth -= 1
            if depth == 0:
                return m.end()
        pos = m.end()
    return -1


def wrap_manual_toc(html_body: str) -> str:
    heading = _TOC_HEADING_RE.search(html_body)
    if not heading:
        return html_body
    list_open = _LIST_OPEN_RE.search(html_body, heading.end())
    if not list_open:
        return html_body
    # Only accept a list that's immediately after the heading (whitespace-only gap)
    gap = html_body[heading.end():list_open.start()]
    if gap.strip():
        return html_body
    list_end = _find_matching_list_end(html_body, list_open.start())
    if list_end < 0:
        return html_body
    return (
        html_body[: heading.end()]
        + gap
        + "<nav class=\"toc-nav\">\n"
        + html_body[list_open.start() : list_end]
        + "\n</nav>"
        + html_body[list_end:]
    )


# --- Shell template -------------------------------------------------------

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap" rel="stylesheet">
<script>try{{var t=localStorage.getItem('spo-theme');if(t)document.documentElement.setAttribute('data-theme',t)}}catch(e){{}}</script>
<script>(function(){{var bgs=['iog-hero-bg-01.jpg','iog-hero-bg-02.jpg','iog-hero-bg-03.jpg'];var pick=bgs[Math.floor(Math.random()*bgs.length)];document.documentElement.style.setProperty('--hero-bg','url("'+pick+'")');}})();</script>
<script>
window.MathJax = {{
  tex: {{
    inlineMath: [['$', '$']],
    displayMath: [['$$', '$$']],
    processEscapes: true
  }},
  options: {{
    skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
  }}
}};
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="assets/site.css?v={asset_ver}">
</head>
<body>
<div class="progress-bar" id="progress"></div>
<nav class="site-nav"><div class="nav-brand">
<a href="index.html" class="nav-brand-home">
<img src="assets/iog-word-marque-white.png" alt="Input | Output Group" class="nav-brand-wordmark">
<span class="nav-brand-sep-vr" aria-hidden="true"></span>
<span class="nav-brand-org"><span class="cbu-dot" aria-hidden="true"></span>Cardano Business Unit</span>
<span class="nav-brand-sep" aria-hidden="true">/</span>
<span class="nav-brand-title">Cardano Reward System V2</span>
</a>
<div class="nav-brand-right">
<button class="theme-toggle" onclick="toggleTheme()" title="Toggle dark/light theme" aria-label="Toggle theme">☀</button>
</div>
</div>
<div class="nav-pages">

<!-- Zone 1 (left anchor) — V2 Specification: the destination, not the conclusion -->
<div class="nav-zone nav-zone-output">
<a href="index.html" class="nav-tab-spec-big{cls_spec}">V2 Specification</a>
</div>

<span class="nav-flow-arrow" aria-hidden="true">←</span>

<!-- Zone 2 — Mainnet Diagnostic (observed reality) -->
<div class="nav-zone nav-zone-diag">
<div class="nav-dd-wrap nav-dd-wrap-light">
<button class="nav-dd-btn-light nav-dd-btn-diag{cls_diag_trigger}" onclick="event.stopPropagation();closeAllDd(this);this.parentElement.classList.toggle('open')" aria-expanded="false">Mainnet Diagnostic ▾</button>
<div class="nav-dd-panel-light nav-dd-panel-diag">
  <div class="nav-dd-stratum">
    <div class="nav-dd-stratum-head">
      <span class="nav-dd-stratum-badge nav-dd-stratum-badge-diagnostic">Mainnet Diagnostic</span>
      <span class="nav-dd-stratum-meta">What mainnet is actually doing — synthesis, Reward-Flow evidence, and the prior report</span>
    </div>
    <a href="observatory.html" class="nav-dd-ref{cls_observatory_title}">
      <span class="nav-dd-ref-title">The Diagnostic<span class="nav-dd-ref-new">New</span></span>
      <span class="nav-dd-ref-cite">Synthesis of observations across the reward pipeline</span>
    </a>
    <a href="census.html" class="nav-dd-ref nav-dd-ref-sub{cls_census}">
      <span class="nav-dd-ref-title">The Staking Census<span class="nav-dd-ref-new">New</span></span>
      <span class="nav-dd-ref-cite">Who holds stake — capital, participation<span class="nav-dd-ref-stage">Evidence</span></span>
    </a>
    <div class="nav-dd-ref-group-label nav-dd-ref-group-label-flow">Reward Flow</div>
    <a href="treasury.html" class="nav-dd-ref nav-dd-ref-sub nav-dd-ref-flow{cls_treasury}">
      <span class="nav-dd-ref-title">Reserves<span class="nav-dd-ref-new">New</span></span>
      <span class="nav-dd-ref-cite">Treasury & pool-pot distribution<span class="nav-dd-ref-stage">Stage 1</span></span>
    </a>
    <a href="pools.html" class="nav-dd-ref nav-dd-ref-sub nav-dd-ref-flow{cls_pools}">
      <span class="nav-dd-ref-title">Pools<span class="nav-dd-ref-new">New</span></span>
      <span class="nav-dd-ref-cite">Distribution gaps across the pool population<span class="nav-dd-ref-stage">Stage 2</span></span>
    </a>
    <a href="operator.html" class="nav-dd-ref nav-dd-ref-sub nav-dd-ref-flow{cls_operator}">
      <span class="nav-dd-ref-title">Operators/Delegators<span class="nav-dd-ref-new">New</span></span>
      <span class="nav-dd-ref-cite">The operator's cut versus the delegator share<span class="nav-dd-ref-stage">Stage 3</span></span>
    </a>
    <div class="nav-dd-ref-group-label">Past Analysis</div>
    <a href="pdf-viewer.html?file=references/previous-analasys/spo-incentives-analysis_lopez-de-lara_2025.pdf" class="nav-dd-ref">
      <span class="nav-dd-ref-title">Nov 2025 — Analysis of Cardano's Incentive Mechanism</span>
      <span class="nav-dd-ref-cite">Lopez de Lara · prior mainnet diagnostic<span class="nav-dd-ref-tag">SD-L</span></span>
      <span class="nav-dd-ref-pdf">PDF</span>
    </a>
  </div>
</div>
</div>
</div>

<span class="nav-flow-arrow" aria-hidden="true">←</span>

<!-- Zone 3 — Design Support (intended mechanism) -->
<div class="nav-zone nav-zone-design">
<div class="nav-dd-wrap nav-dd-wrap-light">
<button class="nav-dd-btn-light nav-dd-btn-design{cls_design_trigger}" onclick="event.stopPropagation();closeAllDd(this);this.parentElement.classList.toggle('open')" aria-expanded="false">Design Support ▾</button>
<div class="nav-dd-panel-light nav-dd-panel-design">
  <div class="nav-dd-stratum">
    <div class="nav-dd-stratum-head">
      <span class="nav-dd-stratum-badge nav-dd-stratum-badge-design">Design Support</span>
      <span class="nav-dd-stratum-meta">The intended mechanism — formal spec + the narrative it never came with</span>
    </div>
    <a href="intended-game.html" class="nav-dd-ref{cls_intended_game}">
      <span class="nav-dd-ref-title">The Intended Game<span class="nav-dd-ref-new">New</span></span>
      <span class="nav-dd-ref-cite">Plain-prose companion to SL-D1 — fills the narrative gap the formal spec left open</span>
    </a>
    <a href="pdf-viewer.html?file=references/design-specs/delegation-incentives-design-spec_kant-brunjes-coutts_2019.pdf" class="nav-dd-ref">
      <span class="nav-dd-ref-title">Delegation Incentives Design Specification</span>
      <span class="nav-dd-ref-cite">Kant · Brünjes · Coutts — 2019<span class="nav-dd-ref-tag">SL-D1</span></span>
      <span class="nav-dd-ref-pdf">PDF</span>
    </a>
  </div>
</div>
</div>
</div>

<span class="nav-flow-arrow" aria-hidden="true">←</span>

<!-- Zone 4 — Research Papers (academic foundations) -->
<div class="nav-zone nav-zone-research">
<div class="nav-dd-wrap nav-dd-wrap-light">
<button class="nav-dd-btn-light nav-dd-btn-research" onclick="event.stopPropagation();closeAllDd(this);this.parentElement.classList.toggle('open')" aria-expanded="false">Research Papers ▾</button>
<div class="nav-dd-panel-light nav-dd-panel-research">
  <div class="nav-dd-stratum">
    <div class="nav-dd-stratum-head">
      <span class="nav-dd-stratum-badge nav-dd-stratum-badge-research">Research Papers</span>
      <span class="nav-dd-stratum-meta">Academic antecedents and adjacent work on reward schemes</span>
    </div>
    <a href="pdf-viewer.html?file=references/research-papers/reward-sharing-schemes_brunjes-kiayias-et-al_2020.pdf" class="nav-dd-ref">
      <span class="nav-dd-ref-title">Reward Sharing Schemes for Stake Pools</span>
      <span class="nav-dd-ref-cite">Brünjes · Kiayias · Koutsoupias · Stouka — 2020<span class="nav-dd-ref-tag">RSS-2020</span></span>
      <span class="nav-dd-ref-pdf">PDF</span>
    </a>
    <a href="pdf-viewer.html?file=references/research-papers/incentives-against-power-grabs_kiayias-et-al_2021.pdf" class="nav-dd-ref">
      <span class="nav-dd-ref-title">Incentives Against Power Grabs</span>
      <span class="nav-dd-ref-cite">Kiayias et al. — 2021<span class="nav-dd-ref-tag">IAPG</span></span>
      <span class="nav-dd-ref-pdf">PDF</span>
    </a>
    <a href="pdf-viewer.html?file=references/research-papers/removing-min-pool-cost_stouka-brunjes-kiayias-koutsoupias_2022.pdf" class="nav-dd-ref">
      <span class="nav-dd-ref-title">Removing the Minimum Pool Cost</span>
      <span class="nav-dd-ref-cite">Stouka · Brünjes · Kiayias · Koutsoupias — 2022<span class="nav-dd-ref-tag">RMPC</span></span>
      <span class="nav-dd-ref-pdf">PDF</span>
    </a>
    <a href="pdf-viewer.html?file=references/research-papers/balancing-participation-decentralization_kiayias-et-al_2024.pdf" class="nav-dd-ref">
      <span class="nav-dd-ref-title">Balancing Participation & Decentralization</span>
      <span class="nav-dd-ref-cite">Kiayias et al. — 2024<span class="nav-dd-ref-tag">BPD</span></span>
      <span class="nav-dd-ref-pdf">PDF</span>
    </a>
  </div>
</div>
</div>
</div>

</div>
<div class="nav-breadcrumb">{breadcrumb_inner}</div>
</nav>
<div class="hero">
  <svg class="hero-schema" viewBox="0 0 1400 400" preserveAspectRatio="xMidYMid slice" aria-hidden="true">
    <defs>
      <pattern id="heroGrid" width="40" height="40" patternUnits="userSpaceOnUse">
        <path d="M 40 0 L 0 0 0 40" fill="none" stroke="rgba(255,255,255,.06)" stroke-width=".5"/>
      </pattern>
    </defs>
    <rect width="1400" height="400" fill="url(#heroGrid)"/>
    <g class="hero-schema-marks" stroke="rgba(229,35,33,.5)" stroke-width=".8" fill="none">
      <path d="M 0 60 L 120 60 L 140 80 L 260 80"/>
      <path d="M 1400 320 L 1260 320 L 1240 300 L 1120 300"/>
      <circle cx="140" cy="80" r="3" fill="#E52321"/>
      <circle cx="1240" cy="300" r="3" fill="#E52321"/>
    </g>
    <g stroke="rgba(22,233,216,.28)" stroke-width=".6" fill="none">
      <path d="M 40 340 L 180 340 L 200 320 L 320 320"/>
      <circle cx="200" cy="320" r="2.5" fill="#16E9D8"/>
    </g>
  </svg>
  <div class="hero-topbar">
    <img src="assets/iog-full-logo-white.png" alt="Input | Output Group" class="hero-full-logo">
    <div class="hero-division">
      <span class="hero-division-dot" aria-hidden="true"></span>
      <span class="hero-division-label">Cardano Business Unit</span>
    </div>
  </div>
  <div class="hero-inner">
    <div class="hero-eyebrow">V2 Reward System &middot; Technical Specification</div>
    <h1>{hero_h1}</h1>
    <div class="sub">{hero_sub}</div>
  </div>
  <div class="hero-bottom-rule" aria-hidden="true"></div>
</div>
<div class="content">{content}</div>
<footer class="site-footer">
  <img src="assets/iog-full-logo-white.png" alt="Input | Output Group" class="footer-logo">
  <div class="footer-division"><span class="cbu-dot" aria-hidden="true"></span>Cardano Business Unit</div>
</footer>
<div class="lightbox-overlay" id="lightbox"><img id="lb-img" src="" alt=""></div>
<a href="#" class="back-top" id="btt">&uarr;</a>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10.9.0/dist/mermaid.min.js"></script>
<script>
if (window.mermaid) {{
  mermaid.initialize({{
    startOnLoad: true,
    theme: 'default',
    securityLevel: 'loose',
    themeVariables: {{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' }},
    flowchart: {{ useMaxWidth: true, htmlLabels: true, curve: 'basis' }}
  }});
}}
</script>
<script src="assets/site.js?v={asset_ver}"></script>
</body>
</html>
"""


# Which active-nav slugs fall under which top-level dropdown
DIAG_ACTIVE = {"observatory", "census", "treasury", "pools", "operator"}
DESIGN_ACTIVE = {"intended-game"}

# Breadcrumb shown beneath the nav to convey hierarchical location.
# Each entry: list of crumbs from most-general → most-specific.
BREADCRUMBS = {
    "spec": ["V2 Specification"],
    "intended-game": ["Design Support", "The Intended Game"],
    "observatory": ["Mainnet Diagnostic", "The Diagnostic"],
    "census": ["Mainnet Diagnostic", "The Staking Census"],
    "treasury": ["Mainnet Diagnostic", "Reward Flow", "Reserves"],
    "pools": ["Mainnet Diagnostic", "Reward Flow", "Pools"],
    "operator": ["Mainnet Diagnostic", "Reward Flow", "Operators/Delegators"],
}


def _render_breadcrumb(active: str, description: str = "") -> str:
    crumbs = BREADCRUMBS.get(active, [])
    if not crumbs:
        return ""
    sep = '<span class="nav-breadcrumb-sep" aria-hidden="true">›</span>'
    parts = []
    for i, crumb in enumerate(crumbs):
        cls = "nav-breadcrumb-item"
        if i == len(crumbs) - 1:
            cls += " nav-breadcrumb-current"
        parts.append(f'<span class="{cls}">{_html.escape(crumb)}</span>')
    rendered = sep.join(parts)
    if description:
        rendered += (
            '<span class="nav-breadcrumb-desc-sep" aria-hidden="true">—</span>'
            f'<span class="nav-breadcrumb-desc">{_html.escape(description)}</span>'
        )
    return rendered


def render_shell(page: dict, content_html: str) -> str:
    active = page["active_nav"]
    nav_map = {
        "spec": "cls_spec",
        "intended-game": "cls_intended_game",
        "observatory": "cls_observatory_title",
        "census": "cls_census",
        "treasury": "cls_treasury",
        "pools": "cls_pools",
        "operator": "cls_operator",
    }
    classes = {v: "" for v in nav_map.values()}
    if active in nav_map:
        classes[nav_map[active]] = " active"
    # Sub-report pages light up the Diagnostic item as "parent-active" so the
    # hierarchy (Diagnostic → sub-report) stays legible in the dropdown panel.
    if active in {"census", "treasury", "pools", "operator"}:
        classes["cls_observatory_title"] = " parent-active"
    cls_diag_trigger = " active" if active in DIAG_ACTIVE else ""
    cls_design_trigger = " active" if active in DESIGN_ACTIVE else ""
    breadcrumb_inner = _render_breadcrumb(active, page.get("hero_sub", ""))
    # Cache-bust CSS/JS using the max mtime of the two asset files so
    # browsers pick up changes without a hard-refresh.
    assets_dir = SITE_DIR / "assets"
    try:
        css_mt = int((assets_dir / "site.css").stat().st_mtime)
    except OSError:
        css_mt = 0
    try:
        js_mt = int((assets_dir / "site.js").stat().st_mtime)
    except OSError:
        js_mt = 0
    asset_ver = str(max(css_mt, js_mt) or int(time.time()))
    return TEMPLATE.format(
        title=page["title"],
        hero_h1=page["hero_h1"],
        hero_sub=page["hero_sub"],
        content=content_html,
        cls_diag_trigger=cls_diag_trigger,
        cls_design_trigger=cls_design_trigger,
        breadcrumb_inner=breadcrumb_inner,
        asset_ver=asset_ver,
        **classes,
    )


# --- CSS/JS extraction (one-time; writes to assets/) ----------------------

_CSS_TAG = re.compile(r"<style>([\s\S]*?)</style>", re.IGNORECASE)
_JS_TAG = re.compile(r"<script>\s*\(function\(\)\{([\s\S]*?)\}\)\(\);\s*</script>", re.IGNORECASE)


def extract_shared_assets() -> None:
    """Extract the big inline CSS block and the bottom JS IIFE from the
    current index.html into assets/site.css and assets/site.js.

    This is a one-time migration: once the assets exist, the generated
    pages all share them via <link> / <script src>.
    """
    assets_dir = SITE_DIR / "assets"
    assets_dir.mkdir(exist_ok=True)
    css_path = assets_dir / "site.css"
    js_path = assets_dir / "site.js"
    if css_path.exists() and js_path.exists():
        ensure_floating_toc_assets()
        return

    idx_html = (SITE_DIR / "index.html").read_text()
    m = _CSS_TAG.search(idx_html)
    if m:
        css_path.write_text(m.group(1).strip() + "\n")
        print(f"  wrote {css_path.relative_to(SITE_DIR)}")
    m = _JS_TAG.search(idx_html)
    if m:
        js_path.write_text("(function(){\n" + m.group(1).strip() + "\n})();\n")
        print(f"  wrote {js_path.relative_to(SITE_DIR)}")
    ensure_floating_toc_assets()


# --- Floating TOC panel: CSS + JS blocks -----------------------------------

_FLOATING_TOC_CSS_MARKER = "/* ── TOC floating panel ──"
_FLOATING_TOC_JS_MARKER = "/* ── TOC floating panel ──"

_FLOATING_TOC_CSS = """
/* ── TOC floating panel ─────────────────────────────── */
/* Hide the inline TOC block when the floating panel is active */
body.has-toc-panel #table-of-contents,
body.has-toc-panel #table-of-contents + .section-body,
body.has-toc-panel > .content > .toc-nav,
body.has-toc-panel .content > h2#table-of-contents + .section-body{display:none}

/* Floating FAB — fixed, top-right, under the sticky nav */
.toc-fab{position:fixed;top:96px;right:20px;width:44px;height:44px;border-radius:50%;
  background:var(--bg);border:1px solid var(--border);color:var(--text-primary);
  display:flex;align-items:center;justify-content:center;cursor:pointer;
  box-shadow:0 4px 14px rgba(0,0,0,.08);z-index:300;
  transition:color .15s,border-color .15s,box-shadow .2s,transform .15s}
.toc-fab:hover{color:var(--infared);border-color:var(--infared);box-shadow:0 6px 18px rgba(229,35,33,.15);transform:translateY(-1px)}
.toc-fab svg{width:20px;height:20px;stroke:currentColor;stroke-width:2;fill:none;stroke-linecap:round;stroke-linejoin:round}
.toc-fab-label{display:none}
[data-theme=dark] .toc-fab{background:var(--bg-panel)}

/* Overlay */
.toc-overlay{position:fixed;inset:0;background:rgba(0,0,0,.35);opacity:0;pointer-events:none;
  transition:opacity .2s;z-index:400}
body.toc-open .toc-overlay{opacity:1;pointer-events:auto}
[data-theme=dark] .toc-overlay{background:rgba(0,0,0,.55)}

/* Side panel */
.toc-panel{position:fixed;top:0;right:0;height:100vh;width:420px;max-width:92vw;
  background:var(--bg);border-left:1px solid var(--border);
  box-shadow:-8px 0 32px rgba(0,0,0,.12);z-index:500;
  transform:translateX(100%);transition:transform .28s cubic-bezier(.4,0,.2,1);
  display:flex;flex-direction:column}
body.toc-open .toc-panel{transform:translateX(0)}

.toc-panel-header{display:flex;align-items:center;justify-content:space-between;
  padding:16px 20px;border-bottom:1px solid var(--border);background:var(--bg-panel);flex-shrink:0}
.toc-panel-title{font:600 13px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  letter-spacing:1.8px;text-transform:uppercase;color:var(--infared)}
.toc-panel-close{background:none;border:1px solid var(--border);border-radius:4px;
  width:30px;height:30px;display:flex;align-items:center;justify-content:center;
  cursor:pointer;color:var(--text-muted);transition:color .15s,border-color .15s}
.toc-panel-close:hover{color:var(--infared);border-color:var(--infared)}
.toc-panel-close svg{width:14px;height:14px;stroke:currentColor;stroke-width:2.2;fill:none;stroke-linecap:round}

.toc-panel-body{flex:1;overflow-y:auto;padding:20px 24px 40px;scrollbar-gutter:stable}
.toc-panel-body::-webkit-scrollbar{width:8px}
.toc-panel-body::-webkit-scrollbar-thumb{background:var(--border);border-radius:4px}
.toc-panel-body::-webkit-scrollbar-thumb:hover{background:var(--text-muted)}

/* Panel-scoped TOC — reuse .toc-nav styling but stripped of the card chrome */
.toc-panel .toc-nav{background:transparent;border:none;padding:0;margin:0}
.toc-panel .toc-nav a{display:block;padding:3px 4px;border-radius:4px;transition:background .1s,color .1s}
.toc-panel .toc-nav a:hover{background:var(--bg-panel);color:var(--infared)}
.toc-panel .toc-nav a.toc-active{color:var(--infared);background:rgba(229,35,33,.08);font-weight:600}
[data-theme=dark] .toc-panel .toc-nav a.toc-active{background:rgba(229,35,33,.15)}

/* Responsive: full-width drawer on mobile, FAB moves to bottom-right */
@media (max-width:720px){
  .toc-fab{top:auto;bottom:80px;right:16px}
  .toc-panel{width:100vw;max-width:100vw;border-left:none}
}
"""

# JS fragment inserted inside the existing IIFE, *before* the "Collapsible TOC
# sub-lists" block, so the clone does not inherit the .toc-toggle decoration.
_FLOATING_TOC_JS = """  /* ── TOC floating panel ── */
  (function initTocPanel(){
    var inlineToc=document.querySelector('.content > .toc-nav')
      || document.querySelector('.content .toc-nav');
    if(!inlineToc) return;
    document.body.classList.add('has-toc-panel');

    var fab=document.createElement('button');
    fab.className='toc-fab';
    fab.type='button';
    fab.setAttribute('aria-label','Open table of contents');
    fab.title='Table of contents';
    fab.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'
      +'<line x1="8" y1="6" x2="21" y2="6"/>'
      +'<line x1="8" y1="12" x2="21" y2="12"/>'
      +'<line x1="8" y1="18" x2="21" y2="18"/>'
      +'<circle cx="4" cy="6" r="1.2" fill="currentColor" stroke="none"/>'
      +'<circle cx="4" cy="12" r="1.2" fill="currentColor" stroke="none"/>'
      +'<circle cx="4" cy="18" r="1.2" fill="currentColor" stroke="none"/>'
      +'</svg>';
    document.body.appendChild(fab);

    var overlay=document.createElement('div');
    overlay.className='toc-overlay';
    overlay.setAttribute('aria-hidden','true');
    document.body.appendChild(overlay);

    var panel=document.createElement('aside');
    panel.className='toc-panel';
    panel.setAttribute('aria-label','Table of contents');
    panel.setAttribute('aria-hidden','true');
    var header=document.createElement('div');
    header.className='toc-panel-header';
    header.innerHTML='<span class="toc-panel-title">Contents</span>'
      +'<button type="button" class="toc-panel-close" aria-label="Close">'
      +'<svg viewBox="0 0 24 24" aria-hidden="true"><line x1="5" y1="5" x2="19" y2="19"/><line x1="19" y1="5" x2="5" y2="19"/></svg>'
      +'</button>';
    var body=document.createElement('div');
    body.className='toc-panel-body';
    var cloned=inlineToc.cloneNode(true);
    cloned.querySelectorAll('.toc-toggle').forEach(function(el){ el.classList.remove('toc-toggle','collapsed'); });
    cloned.querySelectorAll('.toc-collapsed').forEach(function(el){ el.classList.remove('toc-collapsed'); });
    cloned.querySelectorAll('li.has-children').forEach(function(el){ el.classList.remove('has-children'); });
    body.appendChild(cloned);
    panel.appendChild(header);
    panel.appendChild(body);
    document.body.appendChild(panel);

    function openPanel(){ document.body.classList.add('toc-open'); panel.setAttribute('aria-hidden','false'); overlay.setAttribute('aria-hidden','false'); }
    function closePanel(){ document.body.classList.remove('toc-open'); panel.setAttribute('aria-hidden','true'); overlay.setAttribute('aria-hidden','true'); }
    fab.addEventListener('click',function(e){ e.stopPropagation(); openPanel(); });
    overlay.addEventListener('click',closePanel);
    header.querySelector('.toc-panel-close').addEventListener('click',closePanel);
    document.addEventListener('keydown',function(e){
      if(e.key==='Escape' && document.body.classList.contains('toc-open')) closePanel();
    });

    cloned.querySelectorAll('a[href^="#"]').forEach(function(a){
      a.addEventListener('click',function(){
        var id=a.getAttribute('href').slice(1);
        var target=document.getElementById(id);
        if(target){
          var cur=target, toExpand=[];
          while(cur && cur!==document.body){
            if(cur.classList && cur.classList.contains('section-body') && cur.classList.contains('collapsed')){
              var toggle=cur.previousElementSibling;
              if(toggle && toggle.classList.contains('section-toggle')) toExpand.push(toggle);
            }
            cur=cur.parentElement;
          }
          toExpand.reverse().forEach(function(t){ t.click(); });
        }
        setTimeout(closePanel,50);
      });
    });

    var links=Array.from(cloned.querySelectorAll('a[href^="#"]'));
    var map=[];
    links.forEach(function(a){
      var id=a.getAttribute('href').slice(1);
      if(!id) return;
      var el=document.getElementById(id);
      if(el) map.push({id:id,link:a,el:el});
    });
    function updateActive(){
      if(map.length===0) return;
      var y=window.scrollY+140;
      var current=map[0];
      for(var i=0;i<map.length;i++){
        var top=map[i].el.getBoundingClientRect().top+window.scrollY;
        if(top<=y) current=map[i]; else break;
      }
      links.forEach(function(a){ a.classList.remove('toc-active'); });
      if(current) current.link.classList.add('toc-active');
    }
    window.addEventListener('scroll',updateActive,{passive:true});
    updateActive();
  })();

"""


def ensure_floating_toc_assets() -> None:
    """Append the floating TOC CSS/JS blocks to the shared assets if missing.

    Idempotent via marker strings. Safe to call on every build.
    """
    assets_dir = SITE_DIR / "assets"
    css_path = assets_dir / "site.css"
    js_path = assets_dir / "site.js"

    if css_path.exists():
        css_text = css_path.read_text()
        if _FLOATING_TOC_CSS_MARKER not in css_text:
            css_path.write_text(css_text.rstrip() + "\n" + _FLOATING_TOC_CSS)
            print(f"  appended floating TOC CSS to {css_path.relative_to(SITE_DIR)}")

    if js_path.exists():
        js_text = js_path.read_text()
        if _FLOATING_TOC_JS_MARKER not in js_text:
            # Insert the JS fragment just before the existing "Collapsible TOC
            # sub-lists" block so the clone is taken from a clean DOM.
            anchor = "  /* ── Collapsible TOC sub-lists"
            idx = js_text.find(anchor)
            if idx == -1:
                # Fallback: append before closing IIFE
                closing = "\n})();"
                idx = js_text.rfind(closing)
                if idx == -1:
                    js_path.write_text(js_text + "\n" + _FLOATING_TOC_JS)
                else:
                    js_path.write_text(js_text[:idx] + "\n" + _FLOATING_TOC_JS + js_text[idx:])
            else:
                js_path.write_text(js_text[:idx] + _FLOATING_TOC_JS + js_text[idx:])
            # Also rewrite the collapsible-subitem selector to skip the panel
            js_text2 = js_path.read_text()
            old_sel = "document.querySelectorAll('.toc-nav li').forEach"
            new_sel = "document.querySelectorAll('.content .toc-nav li').forEach"
            if old_sel in js_text2:
                js_path.write_text(js_text2.replace(old_sel, new_sel))
            print(f"  injected floating TOC JS into {js_path.relative_to(SITE_DIR)}")


# --- Figure sync ----------------------------------------------------------


def sync_figures() -> None:
    """Mirror figure directories from the MD sources into generated-website/.

    Convention: strip the leading ``diagnostic/`` from source paths.
    """
    source_roots = [
        # (src_dir_rel_to_REPO_ROOT, dst_dir_rel_to_SITE_DIR)
        ("diagnostic/main-flow/figures", "main-flow/figures"),
        ("diagnostic/sub-flows/census/mainnet-analysis/figures",
         "sub-flows/census/mainnet-analysis/figures"),
        ("diagnostic/sub-flows/operator-delegator-distribution/mainnet-analysis/figures",
         "sub-flows/operator-delegator-distribution/mainnet-analysis/figures"),
        ("diagnostic/sub-flows/pools-distribution/mainnet-analysis/figures",
         "sub-flows/pools-distribution/mainnet-analysis/figures"),
        ("diagnostic/sub-flows/treasury-and-pool-pots-distribution/mainnet-analysis/figures",
         "sub-flows/treasury-and-pool-pots-distribution/mainnet-analysis/figures"),
        ("the-intended-game/figures", "the-intended-game/figures"),
    ]

    for src_rel, dst_rel in source_roots:
        src = REPO_ROOT / src_rel
        dst = SITE_DIR / dst_rel
        if not src.exists():
            continue
        dst.mkdir(parents=True, exist_ok=True)
        copied = 0
        for f in src.iterdir():
            if f.is_file() and f.suffix.lower() in {".png", ".jpg", ".jpeg", ".svg", ".gif", ".webp"}:
                target = dst / f.name
                # Only copy if changed
                if (not target.exists()) or (f.stat().st_mtime > target.stat().st_mtime):
                    shutil.copy2(f, target)
                    copied += 1
        if copied:
            print(f"  synced {copied} figures: {src_rel} → {dst_rel}")


def sync_references() -> None:
    """Mirror ``references/`` PDFs with their subfolder structure.

    The nav bar links to flat paths (``references/foo.pdf``) while source MDs
    reference subfolders (``references/research-papers/foo.pdf``). Both need
    to work: we keep the flat mirror already in place and additionally copy
    each PDF into its subfolder location.
    """
    src_root = REPO_ROOT / "references"
    dst_root = SITE_DIR / "references"
    if not src_root.exists():
        return
    copied = 0
    for sub in src_root.iterdir():
        if not sub.is_dir():
            continue
        dst_sub = dst_root / sub.name
        dst_sub.mkdir(parents=True, exist_ok=True)
        for f in sub.iterdir():
            if f.is_file() and f.suffix.lower() == ".pdf":
                target = dst_sub / f.name
                if (not target.exists()) or (f.stat().st_mtime > target.stat().st_mtime):
                    shutil.copy2(f, target)
                    copied += 1
    if copied:
        print(f"  synced {copied} reference PDFs (subfolder mirror)")


# --- Main -----------------------------------------------------------------


# GitHub-style admonitions: `> [!TYPE]\n> body` becomes a styled callout.
_ADMON_RE = re.compile(
    r'<blockquote>\s*<p>\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*(.*?)</p>\s*(.*?)</blockquote>',
    re.IGNORECASE | re.DOTALL,
)


def promote_admonitions(html_body: str) -> str:
    def _sub(m: re.Match) -> str:
        kind = m.group(1).lower()
        first_para = m.group(2).strip()
        rest = m.group(3).strip()
        first = f"<p>{first_para}</p>" if first_para else ""
        return (
            f'<div class="admon admon-{kind}">'
            f'<div class="admon-label">{kind.title()}</div>'
            f"{first}{rest}"
            f"</div>"
        )

    return _ADMON_RE.sub(_sub, html_body)


def build_page(page: dict) -> Path:
    src_md = REPO_ROOT / page["md"]
    if not src_md.exists():
        raise FileNotFoundError(f"Source MD not found: {src_md}")

    md_text = src_md.read_text()
    md_text = preprocess_md(md_text, src_md)
    # Strip the first top-level H1 so the body doesn't duplicate the banner
    # title rendered by render_shell. Keeps the README self-sufficient on
    # GitHub while the website relies on the hero banner for the page title.
    md_text = re.sub(r"\A(?:\s*\n)*#\s+[^\n]*\n+", "", md_text, count=1)
    content_html = md_to_html(md_text)
    content_html = wrap_manual_toc(content_html)
    content_html = promote_admonitions(content_html)

    full = render_shell(page, content_html)
    out = SITE_DIR / page["html"]
    out.write_text(full)
    return out


def main(argv: list[str]) -> int:
    slugs = [a for a in argv[1:] if not a.startswith("-")]
    wanted = PAGES if not slugs else [p for p in PAGES if p["slug"] in slugs]
    if slugs and len(wanted) != len(slugs):
        missing = set(slugs) - {p["slug"] for p in wanted}
        print(f"Unknown slugs: {sorted(missing)}", file=sys.stderr)
        return 2

    print("Extracting shared assets (one-off)…")
    extract_shared_assets()
    print("Syncing figures…")
    sync_figures()
    print("Syncing reference PDFs…")
    sync_references()

    print(f"Building {len(wanted)} page(s)…")
    for page in wanted:
        print(f"  {page['slug']:16s} ← {page['md']}")
        out = build_page(page)
        print(f"  {' ':16s}  → {out.relative_to(SITE_DIR)}")
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
