#!/usr/bin/env python3
"""Normalize multi-level section numbering across the report MDs.

Top-level numbers (e.g. ``## 1. Foo``) already carry a trailing dot.
Multi-level numbers (``1.2``, ``1.2.3``, ``1.2.4.1.5``) currently do
not — this script appends a trailing dot to them so the convention is
consistent.

Two patterns are touched:

1. TOC entries: ``- [1.2 Title](#anchor)`` → ``- [1.2. Title](#anchor)``
2. Section headings: ``### 1.2 Title`` → ``### 1.2. Title``

The slug auto-generated by python-markdown's TOC extension drops dots
when building anchors, so adding a trailing dot does not change any
anchor — the existing ``(#12-title)`` links stay valid.

Idempotent: re-running the script on already-normalized files makes
no change (the regex requires a space after the number, and ``1.2.``
is followed by ``.`` then space, not a space).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_ROOT = REPO_ROOT / "reward-system-spec"

# Skip the November 2025 frozen report.
SKIP_DIRS = {"report-november-2025"}

# `1.2`, `1.2.3`, ... — at least two segments (so single-digit `1`
# alone is left untouched).
NUM_RE = r"\d+(?:\.\d+)+"

# TOC: leading whitespace + `- [<num> <title>](<anchor>)`
TOC_RE = re.compile(rf"(\[)(?P<num>{NUM_RE})( )", re.MULTILINE)

# Heading: `^#+ <num> <title>`
HEADING_RE = re.compile(
    rf"^(?P<hash>#+\s+)(?P<num>{NUM_RE})( )", re.MULTILINE
)


def normalize(text: str) -> tuple[str, int]:
    """Return (new_text, num_changes)."""
    n = 0

    def add_dot_toc(m: re.Match) -> str:
        nonlocal n
        n += 1
        return f"{m.group(1)}{m.group('num')}. "

    def add_dot_heading(m: re.Match) -> str:
        nonlocal n
        n += 1
        return f"{m.group('hash')}{m.group('num')}. "

    text = TOC_RE.sub(add_dot_toc, text)
    text = HEADING_RE.sub(add_dot_heading, text)
    return text, n


def main() -> int:
    total_files = 0
    total_changes = 0
    for md_path in SPEC_ROOT.rglob("*.md"):
        rel = md_path.relative_to(REPO_ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        before = md_path.read_text()
        after, n = normalize(before)
        if n and after != before:
            md_path.write_text(after)
            total_files += 1
            total_changes += n
            print(f"  {rel}: +{n} dots")
    print(f"\nNormalized {total_changes} numbers across {total_files} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
